name: pose_diffusion

train_data_path: /home/sohiyel/Projects/DiffGesture-AQGT/data/SmallAQGT/train
val_data_path: /home/sohiyel/Projects/DiffGesture-AQGT/data/SmallAQGT/val
test_data_path: /home/sohiyel/Projects/DiffGesture-AQGT/data/SmallAQGT/test

wordembed_dim: 300
wordembed_path: /home/sohiyel/Projects/fasttext//crawl-300d-2M-subword.bin

model_save_path: output/train_diffusion_aqgt
random_seed: -1

pose_dim: 159
diff_hidden_dim: 512
block_depth: 8

# model params
model: pose_diffusion

hidden_size: 300
input_context: audio

classifier_free: True
null_cond_prob: 0.1

# train params
epochs: 500
batch_size: 128
learning_rate: 0.0005

# eval params
eval_net_path: output/TED_AQGT_output/AE-cos1e-3/gesture_autoencoder_checkpoint_best.bin

# dataset params
motion_resampling_framerate: 15
n_poses: 34
n_pre_poses: 4
subdivision_stride: 10
loader_workers: 4